### ISSUE TITLE
Invalid signature

### ISSUE THREAD

**Issue by unhappychoice** [dtaniwaki/akka-pusher#28]
https://github.com/dtaniwaki/akka-pusher/blob/master/src/main/scala/com/github/dtaniwaki/akka_pusher/PusherClient.scala#L189

`queryString()` returns `Optional` value.
So, I think this causes Invalid signature problem

**Comment by dtaniwaki** [comment]
Uh, let me check it.

**Comment by dtaniwaki** [comment]
Yes... it was string before..
http://doc.akka.io/api/akka-stream-and-http-experimental/1.0/index.html#akka.http.javadsl.model.Uri

**Comment by dtaniwaki** [comment]
Fixed and released v0.2.12. Thank you for reporting the issue.
