### ISSUE TITLE
Usage like pusher-java-client bind

### ISSUE THREAD

**Issue by blbradley** [dtaniwaki/akka-pusher#31]
Hello!

I'm having trouble understanding how to use this library vs using the pusher java client. How does one use this library compared to using `bind`?

**Comment by dtaniwaki** [comment]
If you want AkkaActor-based system, you can consider to use it this library.

**Comment by blbradley** [comment]
I do! However, I'm not sure how to do something like java-pusher-client's
`bind`. Can I do something similar to `bind` with this library?

**Comment by dtaniwaki** [comment]
I have made a sample app to use this library.
https://github.com/dtaniwaki/akka-pusher-play-app

You can make any endpoint to wait the webhook calls from pusher and handle them.
https://github.com/dtaniwaki/akka-pusher-play-app/blob/eadcb7f283d92cec403984ef4e17ff8d4b7b46bc/app/controllers/PusherActorController.scala#L45

This library doesn't connect to the websockets.

**Comment by dtaniwaki** [comment]
I would say [pusher-java-client](https://github.com/pusher/pusher-websocket-java) is a client side library while this library is a server side.

**Comment by blbradley** [comment]
That makes more sense. Thank you! Close #31.

**Comment by dtaniwaki** [comment]
You're welcome. Please give me any feedback using this library.

**Comment by blbradley** [comment]
I actually won't be using it because I need a client side library. Maybe
you could try to introduce a client side API sometime if you have the need.
